services:
    odtk-python:
        image: ansys/odtk/odtk-python:13.0.1-ubi8
        build:
            context: .
            args:
                baseImage: ansys/odtk/odtk-runtime:13.0.1-ubi8
        env_file: ../configuration/licensing.env
