services:
    odtk-webservice:
        image: ansys/odtk/odtk-webservice:13.0.1-ubi8
        build:
            context: .
            args:
                baseImage: ansys/odtk/odtk-python:13.0.1-ubi8
        env_file: ../configuration/licensing.env
        ports:
            - 5000:5000
